### ISSUE TITLE
Do I install this if I want a "wallet" that runs on node.js?

### ISSUE THREAD

**Issue by sunk818** [Bushstar/artbytecore-node#1]
Just want to help SegWit become enabled sooner by throwing up a few more instances.

**Comment by Bushstar** [comment]
Adding more nodes to the network will not make SegWit activate sooner, all SegWit needs is more hash power on the 0.13 client, specifically 80% of the hash power, or the people mining on 0.8 to upgrade.

https://www.artbyte.me/segwitcsv-progress-tracker/

There was an error with 0.13.0.0 client that caused it to crash, we were up to  85% of the last 1,000 blocks being SegWit and then we dropped down to ~75% as we are now, I think someone (not a known pool) with a decent setup hit the crash in 0.13 and downgraded to 0.8 bringing us below the activation threshold. The 0.13.0.1 client fixes that crash but we need whomever downgraded to upgrade again.

If you run this it will download and run a custom 0.13 binary the same as running the client from the website, there are headless daemons available on the main website if you want to run some of them. 0.13.0.1 available from the link below.

https://www.artbyte.me/get-started/

**Comment by sunk818** [comment]
I got 5 linux nodes running now. artbyted is verifying the blockchain, but hopefully will be useful soon.

sudo apt-get install unzip

wget https://downloads.artbyte.me/artbyted-0.13.0.1-linux64.tar.gz
tar xvf artbyted-0.13.0.1-linux64.tar.gz
mkdir ~/.applebyte
cd ~/.applebyte
wget https://quickstart.artbyte.me/blockchain.zip
unzip blockchain.zip
rm -f blockchain.zip
cd ~/artbyted-0.13.0.1-linux64
./artbyted &

**Comment by Bushstar** [comment]
Use this to run the client instead of using &

./artbyted --daemon

We need lots of L3+ miners.
