### ISSUE TITLE
What may have been lost

### ISSUE THREAD

**Issue by cqtenq** [Bushstar/artbytecore-node#2]
When I run install , I have a problem.

 npm install -g artbytecore-node

WARN Debug:
npm WARN lifecycle artbytecore-node@3.1.16~preinstall: cannot run in wd %s %s (wd=%s) artbytecore-node@3.1.16 ./scripts/download /usr/local/lib/node_modules/.staging/artbytecore-node-db184c33

npm ERR:
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "artbytecore-node"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules/artbytecore-node/bin/artbyted
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/artbytecore-node/bin/artbyted'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/artbytecore-node/bin/artbyted'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.

**Comment by Bushstar** [comment]
Hi Lizhi,

How are you?

I install this package locally using git clone and then run the other commands as normal like..

./bin/artbytecore-node create api
cd api
../bin/artbytecore-node install artbyte-api
../bin/artbytecore-node start

I never got to finish porting the Insight and Bitcore packages for ArtByte, the explorer did not display and then my time with ArtByte came to an end. If you find any issues please push them to GitHub and I can update the NPM packages.

**Comment by cqtenq** [comment]
Helo,bushnell, I'm lizhi.
Thank you for your reply.I'm installing blockchain explorer.
